---

- name: 'RedHat: Add elastic.co GPG key'
  rpm_key:
    state: present
    key: "{{ elastic_repo__local_gpgkey | ternary('/tmp/' + elastic_gpg_file , elastic_gpg_url) }}"

- name: 'RedHat: Create elastic.co yum repo'
  yum_repository:
    name: elastic.co
    description: Elasticsearch repository for 5.x packages
    baseurl: "{{ elastic_yum_repo_url }}"
    enabled: yes
    gpgcheck: yes
    # gpgkey: "{{ elastic_gpg_url }}"
    skip_if_unavailable: yes
    timeout: 10
    state: present
